### ISSUE TITLE
CLI Error

### ISSUE THREAD

**Issue by victorioferrario** [charleslbryant/hello-react-and-typescript#1]
After following the instructions, I kept getting the following error when running "gulp". 
`  /usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3`

This fixed the problem.
`npm install -g "gulpjs/gulp-cli#4.0"`

**Comment by charleslbryant** [comment]
I'll update thanks for pointing that out.
