### ISSUE TITLE
Git Error

### ISSUE THREAD

**Issue by stephen-oconnor** [charleslbryant/hello-react-and-typescript#3]
I'm getting the following error when running ```npm install```.

npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0:
npm ERR! code 128
npm ERR! Command failed: git -c core.longpaths=true rev-list -n1 4.0
npm ERR! fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stephen.oconnor\AppData\Roaming\npm-cache\_logs\2017-05-18T15_34_43_334Z-debug.log

Any ideas?

**Comment by stephen-oconnor** [comment]
[This](https://github.com/zurb/foundation-cli/issues/36) helped for me.

**Comment by stephen-oconnor** [comment]
More issues sorry, does this repo/tutorial still work?

The above link fixed the first issue however, ```tsd install``` gives me the following error:

'tsd' is not recognized as an internal or external command,
operable program or batch file.

And ```gulp``` give me the following error:

error TS5023: Unknown compiler option 'compileOnSave'.
[17:01:53] Using gulpfile ~\Documents\PATH\charles-bryant-react-typescript\hello-react-and-typescript\gulpfile.js
C:\Users\stephen.oconnor\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\stephen.oconnor\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Then if I do ```npm install -g "gulpjs/gulp-cli#4.0"``` I get the first error again.

**Comment by NamitYadav** [comment]
Hi, is there any update on this? After changing the `gulp-cli` version to `"^1.2.1"`, i am able to `npm install` and `tsd install`, but on running `gulp`, i get the following error:

`error TS5023: Unknown compiler option 'compileOnSave'.
/Users/namit/workspace/Projects/hello-react-and-typescript/gulpfile.js:118
gulp.task('default', gulp.series('clean', gulp.parallel('html', 'css', 'img'), 'typescript', 'lint', 'js', 'connect', 'watch'));
                                               ^

TypeError: gulp.parallel is not a function
    at Object.<anonymous> (/Users/namit/workspace/Projects/hello-react-and-typescript/gulpfile.js:118:48)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)`

**Comment by charleslbryant** [comment]
Sorry, I stopped developing this as I don't actively use React or Typescript. I remeber that I injected some bugs and I never corrected them. There were other React Typescript examples that I found after I did this that may provide better example of how to accomplish it.

I wanted to updgrade everything and use webpack. If you ever get a sample up and going on Github, let me know.

-
https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

- 
http://javascriptplayground.com/blog/2017/04/react-typescript/

- https://medium.com/@fay_jai/getting-started-with-reactjs-typescript-and-webpack-95dcaa0ed33c
